import { Scene } from "@babylonjs/core/scene";
import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera";
export declare class LabelManager {
    private _canvas;
    private _scene;
    private _ymax;
    private _camera;
    private _labelControlBox;
    private _editLabelContainer;
    private _editLabelForms;
    private _addLabelTextInput;
    private _labels;
    private _labelBackgrounds;
    private _labelTexts;
    private _showLabels;
    private _labelSize;
    fixed: boolean;
    constructor(canvas: HTMLCanvasElement, scene: Scene, ymax: number, camera: ArcRotateCamera);
    private _createLabelForms;
    update(): void;
    toggleLabelControl(): void;
    private _addLabelBtnClick;
    addLabel(text: string, position?: number[]): number;
    private makeDraggable;
    addLabels(labelList: [[number, number, number, string]]): void;
    private _editLabelText;
    private _removeLabel;
    exportLabels(): any[];
    fixLabels(): void;
    unfixLabels(): void;
}
